@startuml Diagrama

class Usuario
class Juego{
    -Mascota Mascota
    -Usuario Usuario
}
class Mascota{
    +Pasear()
    -Felicidad Felicidad
}
class Felicidad
class Porcentaje{
    -Numero numero
    +Incrementar (numero)
    +Disminuir (numero)
    +Imprimir ()
}

Usuario o-- Mascota
Mascota *-- Felicidad
Juego *-- Usuario
Juego *-- Mascota
Felicidad --|> Porcentaje
Porcentaje *-- Numero
Juego *-- Mascota
Felididad --|> Porcentaje

@enduml